/* ============================================================================
   Penumbra — language-tint mirror
   Copies the focused editor's language id onto .monaco-workbench as
   data-active-lang, so chrome surfaces (tabs, status bar, sidebar markers,
   activity bar glow, scrollbars, find widget) can pick up var(--void-tint)
   from the matching CSS rule generated by build.mjs.

   Loaded by Custom UI Style via custom-ui-style.external.imports.
   ========================================================================== */

(() => {
  "use strict";

  const ATTR = "data-active-lang";

  const findWorkbench = () => document.querySelector(".monaco-workbench");

  const detectLang = () => {
    // 1. Focused editor wins.
    const focused = document.querySelector(".monaco-editor.focused");
    const fromFocused = focused?.getAttribute("data-mode-id");
    if (fromFocused) return fromFocused;

    // 2. Fall back to any visible editor in the active group.
    const active = document.querySelector(
      ".editor-group-container.active .monaco-editor[data-mode-id]"
    );
    const fromActive = active?.getAttribute("data-mode-id");
    if (fromActive) return fromActive;

    // 3. Any editor at all — covers single-editor windows.
    const any = document.querySelector(".monaco-editor[data-mode-id]");
    return any?.getAttribute("data-mode-id") ?? null;
  };

  let lastLang = null;
  const sync = () => {
    const wb = findWorkbench();
    if (!wb) return;
    const lang = detectLang();
    if (lang === lastLang) return;
    lastLang = lang;
    if (lang) wb.setAttribute(ATTR, lang);
    else wb.removeAttribute(ATTR);
  };

  // Throttle: at most one sync per animation frame.
  let pending = false;
  const requestSync = () => {
    if (pending) return;
    pending = true;
    requestAnimationFrame(() => {
      pending = false;
      sync();
    });
  };

  const start = () => {
    const wb = findWorkbench();
    if (!wb) {
      // Workbench not mounted yet — try again shortly.
      setTimeout(start, 250);
      return;
    }

    // Watch for tab changes, focus moves, and mode switches.
    const observer = new MutationObserver(requestSync);
    observer.observe(wb, {
      subtree: true,
      attributes: true,
      attributeFilter: ["class", "data-mode-id"],
      childList: true,
    });

    // Focus/blur covers Cmd-clicks into editors.
    document.addEventListener("focusin", requestSync, true);
    document.addEventListener("click", requestSync, true);

    sync();
  };

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", start, { once: true });
  } else {
    start();
  }
})();
